export const mockData = [
  {
    id: 1,
    symbol: "TSLA",
    price: 200,
    rateChange: 0.25,
    direction: "increased",
    riskLevel: "high risk",
    industry: "Automotive",
    marketCap: "Large Cap",
    strategy: "Long",
    assets: "Stocks",
  },
  {
    id: 2,
    symbol: "AAPL",
    price: 150,
    rateChange: -0.15,
    direction: "decreased",
    riskLevel: "low risk",
    industry: "Technology",
    marketCap: "Large Cap",
    strategy: "Short Reports",
    assets: "Stocks",
  },
  {
    id: 3,
    symbol: "GOOGL",
    price: 2500,
    rateChange: 0.10,
    direction: "increased",
    riskLevel: "mid risk",
    industry: "Communication",
    marketCap: "Large Cap",
    strategy: "Big Option Buys",
    assets: "Options",
  },
  {
    id: 4,
    symbol: "AMZN",
    price: 3300,
    rateChange: -0.05,
    direction: "decreased",
    riskLevel: "mid risk",
    industry: "Consumer Discretionary",
    marketCap: "Large Cap",
    strategy: "Merger Arbitrage",
    assets: "Futures",
  },
  {
    id: 5,
    symbol: "NFLX",
    price: 500,
    rateChange: 0.30,
    direction: "increased",
    riskLevel: "high risk",
    industry: "Entertainment",
    marketCap: "Mid Cap",
    strategy: "Big Option Buys",
    assets: "Options",
  },
  {
    id: 6,
    symbol: "JNJ",
    price: 160,
    rateChange: 0.20,
    direction: "increased",
    riskLevel: "low risk",
    industry: "Healthcare",
    marketCap: "Large Cap",
    strategy: "Short Reports",
    assets: "Stocks",
  },
  {
    id: 7,
    symbol: "XOM",
    price: 60,
    rateChange: -0.10,
    direction: "decreased",
    riskLevel: "mid risk",
    industry: "Energy",
    marketCap: "Large Cap",
    strategy: "Merger Arbitrage",
    assets: "Futures",
  },
  {
    id: 8,
    symbol: "WMT",
    price: 140,
    rateChange: 0.05,
    direction: "increased",
    riskLevel: "low risk",
    industry: "Consumer Staples",
    marketCap: "Large Cap",
    strategy: "Short Reports",
    assets: "Stocks",
  },
  {
    id: 9,
    symbol: "SPG",
    price: 120,
    rateChange: -0.20,
    direction: "decreased",
    riskLevel: "high risk",
    industry: "Real Estate",
    marketCap: "Large Cap",
    strategy: "Merger Arbitrage",
    assets: "Stocks",
  },
  {
    id: 10,
    symbol: "BA",
    price: 230,
    rateChange: 0.15,
    direction: "increased",
    riskLevel: "mid risk",
    industry: "Industrials",
    marketCap: "Large Cap",
    strategy: "Big Option Buys",
    assets: "Options",
  },
  {
    id: 11,
    symbol: "DUK",
    price: 100,
    rateChange: -0.05,
    direction: "decreased",
    riskLevel: "low risk",
    industry: "Utilities",
    marketCap: "Large Cap",
    strategy: "Merger Arbitrage",
    assets: "Futures",
  },
  {
    id: 12,
    symbol: "GS",
    price: 250,
    rateChange: 0.30,
    direction: "increased",
    riskLevel: "high risk",
    industry: "Financials",
    marketCap: "Large Cap",
    strategy: "Big Option Buys",
    assets: "Options",
  },
  {
    id: 13,
    symbol: "LMT",
    price: 400,
    rateChange: -0.10,
    direction: "decreased",
    riskLevel: "mid risk",
    industry: "Industrials",
    marketCap: "Large Cap",
    strategy: "Merger Arbitrage",
    assets: "Futures",
  },
  {
    id: 14,
    symbol: "META",
    price: 250,
    rateChange: 0.25,
    direction: "increased",
    riskLevel: "high risk",
    industry: "Communication",
    marketCap: "Large Cap",
    strategy: "Short Reports",
    assets: "Stocks",
  },
  {
    id: 15,
    symbol: "PFE",
    price: 50,
    rateChange: -0.05,
    direction: "decreased",
    riskLevel: "low risk",
    industry: "Healthcare",
    marketCap: "Large Cap",
    strategy: "Merger Arbitrage",
    assets: "Stocks",
  },
];

export const filterMockData = {
  industries: [
    'Health Care',
    'Materials',
    'Energy',
    'Consumer Discretionary',
    'Consumer Stapies',
    'Real Estate',
    'IT',
    'Communication',
    'Industries',
    'Utilities',
    'Financials',
  ],
  marketCaps: [
    'Micro',
    'Small',
    'Large',
  ],
  riskLevels: [
    'Low Risk',
    'Mid Risk',
    'High Risk',
  ],
  strategies: [
    'Big Option Buys',
    'Merger Arbitrage',
    'Short Reports',
  ],
  assets: [
    'Stocks',
    'Options',
    'Futures',
  ],
};


export const imageMapping = {
  "healthcare":'../../icons/Healthcare.svg',
  "materials": "../../icons/Materials.svg",
  "energy": "../../icons/Energy.svg",
  "consumerdiscretionary": "../../icons/ConsumerDesc.svg",
  "consumerstapies": "../../icons/ConsumerStap.svg",
  "realestate": "../../icons/RealEstate.svg",
  "it": "../../icons/It.svg",
  "communication": "../../icons/Communication.svg",
  "industries": "../../icons/Industries.svg",
  "utilities": "../../icons/Utilities.svg",
  "financials": "../../icons/Financials.svg",
}